# compiles weights.json into model.css + index.html + expected.json.
# style.css is hand written. rerun me after every retrain.
#
# the shape of the thing: every token position is one nesting level of the
# dom. each level's cell runs the full transformer step in shared css rules
# (rmsnorm, int8 matmuls in calc, swiglu, lm head, argmax). what CAN'T be
# shared is anything positional: rope angles are literals per level, the kv
# cache write goes to that level's named slots, and attention reads however
# many positions exist below it. those get generated per level, which is why
# this file emits a few megabytes. attention is o(t^2) in css just like in
# real life, except here the t^2 is bytes.

import json
import math

w = json.load(open("weights.json"))
VOCAB = w["vocab"]
V = len(VOCAB)
T, PROMPT = w["T"], w["PROMPT"]
GEN = T - PROMPT
D, L, HEADS, HD, MLP = w["D"], w["L"], w["HEADS"], w["HD"], w["MLP"]
EPS = w["eps"]
PJ = w["P"]
COS, SIN = w["cos"], w["sin"]
Q = w["Q"]
S = w["S"]
NORMS = w["norms"]
N_PARAMS = w["n_params"]
stoi = {t: i for i, t in enumerate(VOCAB)}
PAD, USR, BOT, END = 0, 1, 2, 3
SQ = math.sqrt(HD)

TIE = 1e-5
SEPS = 1e-7

QUESTIONS = [
    "hello",
    "who are you ?",
    "how do you work ?",
    "what is css ?",
    "do you like treats ?",
    "tell me about your day",
    "are you a real llm ?",
    "can you help me ?",
    "who is yipsy ?",
    "do you use javascript ?",
    "good girl",
    "tell me a joke",
]
ROLLS = [("r1", 3, "🎾"), ("r2", 47, "🦴"), ("r3", 101, "🧸"), ("r4", 199, "🍖")]
TAMPS = [("sleepy", 0.6), ("waggy", 1.6), ("zoomies", 3.2)]
DEFAULT_Q, DEFAULT_ROLL, DEFAULT_TAMP = 1, "r1", "waggy"

# dequantized float weights, exactly what the stylesheet computes with
DQ = {k: [[Q[k][i][j] * S[k][j] for j in range(len(S[k]))] for i in range(len(Q[k]))] for k in Q}


def fmt(x):
    # full double precision, trimmed. parity with python floats depends on it
    r = repr(float(x))
    return "0" if r in ("0.0", "-0.0") else r


def sgn_term(x):
    return f"- {fmt(-x)}" if x < 0 else f"+ {fmt(x)}"


# --- css --------------------------------------------------------------------

css = [
    "/* model.css — generated by build.py, do not hand edit.",
    f"   qwennie herself: {N_PARAMS} parameters. decoder only transformer,",
    f"   {L} layers, {HEADS} heads, d {D}, rope, rmsnorm, swiglu, int8 matmuls.",
    "   the kv cache is inherited custom properties. attention is unrolled",
    "   per position because css has no loops, only consequences. */",
    "",
]

reg = []


def prop(name, syntax="<number>", inherits=False, initial="0"):
    reg.append(f'@property {name} {{ syntax: "{syntax}"; inherits: {"true" if inherits else "false"}; initial-value: {initial}; }}')


# plumbing
prop("--tk", "<integer>", True, "0")
prop("--np", "<integer>", True, "0")
prop("--sd", "<number>", True, "3")
prop("--s2", "<number>", True, "3")
prop("--tamp", "<number>", True, "1.6")
prop("--dn", "<number>", True, "0")
prop("--d2", "<number>", True, "0")
prop("--probe")

# per cell working registers, layer prefixed
def lp(l):
    return "" if l == 0 else "u"


for l in range(L):
    for nm in ("x", "a", "q", "k", "v", "qr", "kr", "o", "om", "xm", "b"):
        for j in range(D):
            prop(f"--{lp(l)}{nm}{j}")
    for nm in ("gt", "up", "sg", "ac"):
        for j in range(MLP):
            prop(f"--{lp(l)}{nm}{j}")
    prop(f"--{lp(l)}r1")
    prop(f"--{lp(l)}r2")
for j in range(D):
    prop(f"--xn{j}")
    prop(f"--uxn{j}")
    prop(f"--f{j}")
prop("--rf")
for k in range(V):
    prop(f"--lg{k}")
prop("--gmx")

# attention scratch: scores per layer/head/position, softmax denominators
for l in range(L):
    for h in range(HEADS):
        for i in range(T - 1):
            prop(f"--s{l}{h}i{i}")
        prop(f"--mx{l}{h}")
        prop(f"--dnm{l}{h}")

# the kv cache. inherited, so every level sees everything written above it
for l in range(L):
    for pos in range(T - 1):
        for j in range(D):
            prop(f"--K{l}p{pos}j{j}", inherits=True)
            prop(f"--V{l}p{pos}j{j}", inherits=True)

css.append("\n".join(reg))
css.append("")

# --- control wiring ---------------------------------------------------------


def encode_prompt(qtext):
    ws = qtext.split()
    return [PAD] * (PROMPT - 2 - len(ws)) + [USR] + [stoi[x] for x in ws] + [BOT]


wire = ["/* radios -> prompt tokens, salt, temperature, chat transcript */"]
for qi, qtext in enumerate(QUESTIONS):
    ids = encode_prompt(qtext)
    for pos in range(PROMPT):
        wire.append(f"#q{qi}:checked ~ .page .pw{pos} {{ --tk: {ids[pos]}; }}")
    wire.append(f'#q{qi}:checked ~ .page .um::before {{ content: "{qtext}"; }}')
for rid, salt, _ in ROLLS:
    wire.append(f"#roll-{rid}:checked ~ .page .chat {{ --sd: {salt}; }}")
for tid, tamp in TAMPS:
    wire.append(f"#tamp-{tid}:checked ~ .page .chat {{ --tamp: {fmt(tamp)}; }}")

ids_all = [f"q{i}" for i in range(len(QUESTIONS))] + [f"roll-{r}" for r, _, _ in ROLLS] + [f"tamp-{t}" for t, _ in TAMPS]
wire.append(", ".join(f'#{i}:checked ~ .page label[for="{i}"]' for i in ids_all)
            + " { background: var(--acc); border-color: var(--acc); color: var(--acc-ink); }")
wire.append(", ".join(f'#{i}:focus-visible ~ .page label[for="{i}"]' for i in ids_all)
            + " { outline: 2px solid var(--acc); outline-offset: 2px; }")
css.append("\n".join(wire))
css.append("")

# --- embeddings -------------------------------------------------------------
# row lookup by the parent wrapper's --tk. values are dequantized here at
# build time; the ints and scales live in weights.json.

emb = ["/* embedding rows */"]
for t in range(V):
    row = "; ".join(f"--x{j}: {fmt(DQ['emb'][t][j])}" for j in range(D))
    emb.append(f"@container style(--tk: {t}) {{ .cl {{ {row}; }} }}")
css.append("\n".join(emb))
css.append("")


# --- the shared transformer step ---------------------------------------------


def matmul_int(dst, src, name, n_in, n_out, extra=""):
    # dst_j = scale_j * (sum_i src_i * int[i][j]) [+ extra]
    lines = []
    q, s = Q[name], S[name]
    for j in range(n_out):
        terms = []
        for i in range(n_in):
            c = q[i][j]
            if c == 0:
                continue
            terms.append(("+ " if c > 0 else "- ") + f"var(--{src}{i})*{abs(c)}")
        # leading literal zero because calc() has no unary minus on var terms.
        # a sum starting "- var(--a0)*12" is a parse error and the whole
        # property silently falls back to 0, which is a very quiet way to
        # lobotomize a dog.
        body = "0 " + " ".join(terms) if terms else "0"
        e = extra.format(j=j) if extra else ""
        lines.append(f"  --{dst}{j}: calc({fmt(s[j])} * ({body}){e});")
    return lines


def rms_lines(rvar, src, n):
    sq = " + ".join(f"var(--{src}{j})*var(--{src}{j})" for j in range(n))
    return [f"  --{rvar}: calc(1 / sqrt(({sq}) / {n} + {fmt(EPS)}));"]


cell = ["/* one transformer step, shared by every level */", ".cl {", "  display: inline;"]
for l in range(L):
    p = lp(l)
    xin = "x" if l == 0 else "xn"
    g1 = NORMS[f"g1{l}"]
    g2 = NORMS[f"g2{l}"]
    cell += rms_lines(f"{p}r1", xin, D)
    for j in range(D):
        cell.append(f"  --{p}a{j}: calc(var(--{xin}{j}) * var(--{p}r1) * {fmt(g1[j])});")
    cell += matmul_int(f"{p}q", f"{p}a", f"wq{l}", D, D)
    cell += matmul_int(f"{p}k", f"{p}a", f"wk{l}", D, D)
    cell += matmul_int(f"{p}v", f"{p}a", f"wv{l}", D, D)
    # rope happens in the per level rules. attention output --{p}o too.
    for j in range(D):
        cell.append(f"  --{p}xm{j}: calc(var(--{xin}{j}) + var(--{p}om{j}));")
    cell += rms_lines(f"{p}r2", f"{p}xm", D)
    for j in range(D):
        cell.append(f"  --{p}b{j}: calc(var(--{p}xm{j}) * var(--{p}r2) * {fmt(g2[j])});")
    cell += matmul_int(f"{p}gt", f"{p}b", f"wg{l}", D, MLP)
    cell += matmul_int(f"{p}up", f"{p}b", f"wu{l}", D, MLP)
    for j in range(MLP):
        cell.append(f"  --{p}sg{j}: calc(var(--{p}gt{j}) / (1 + exp(-1 * var(--{p}gt{j}))));")
        cell.append(f"  --{p}ac{j}: calc(var(--{p}sg{j}) * var(--{p}up{j}));")
    out = "xn" if l == 0 else "uxn"
    # down projection with the residual folded in
    qd, sd = Q[f"wd{l}"], S[f"wd{l}"]
    for j in range(D):
        terms = []
        for i in range(MLP):
            c = qd[i][j]
            if c == 0:
                continue
            terms.append(("+ " if c > 0 else "- ") + f"var(--{p}ac{i})*{abs(c)}")
        body = "0 " + " ".join(terms) if terms else "0"
        cell.append(f"  --{out}{j}: calc(var(--{p}xm{j}) + {fmt(sd[j])} * ({body}));")
gf = NORMS["gf"]
cell += rms_lines("rf", "uxn", D)
for j in range(D):
    cell.append(f"  --f{j}: calc(var(--uxn{j}) * var(--rf) * {fmt(gf[j])});")
cell.append("}")
css.append("\n".join(cell))
css.append("")

# wo matmul needs its own name (--om) because attention out --o is per level
womm = [".cl {"]
for l in range(L):
    p = lp(l)
    womm += matmul_int(f"{p}om", f"{p}o", f"wo{l}", D, D)
womm.append("}")
css.append("\n".join(womm))
css.append("")

# --- per level rules: rope, kv write, attention read --------------------------

lev = ["/* positional rules. rope angles and attention width are per level */"]
for pos in range(T - 1):
    lines = [f".cl.p{pos} {{"]
    for l in range(L):
        p = lp(l)
        # rotate q and k with this position's angles, write the kv slots
        for h in range(HEADS):
            for fq in range(HD // 2):
                c, s = fmt(COS[pos][fq]), fmt(SIN[pos][fq])
                e, o = h * HD + 2 * fq, h * HD + 2 * fq + 1
                lines.append(f"  --{p}qr{e}: calc(var(--{p}q{e})*{c} - var(--{p}q{o})*{s});")
                lines.append(f"  --{p}qr{o}: calc(var(--{p}q{e})*{s} + var(--{p}q{o})*{c});")
                lines.append(f"  --{p}kr{e}: calc(var(--{p}k{e})*{c} - var(--{p}k{o})*{s});")
                lines.append(f"  --{p}kr{o}: calc(var(--{p}k{e})*{s} + var(--{p}k{o})*{c});")
        for j in range(D):
            lines.append(f"  --K{l}p{pos}j{j}: var(--{p}kr{j});")
            lines.append(f"  --V{l}p{pos}j{j}: var(--{p}v{j});")
        # attention over positions 0..pos (this level's own k comes from its
        # freshly written slot vars? no — from the local --kr, same values)
        for h in range(HEADS):
            for i in range(pos + 1):
                dot = " + ".join(
                    f"var(--{p}qr{h*HD+j})*var(--K{l}p{i}j{h*HD+j})" if i < pos else
                    f"var(--{p}qr{h*HD+j})*var(--{p}kr{h*HD+j})"
                    for j in range(HD)
                )
                lines.append(f"  --s{l}{h}i{i}: calc(({dot}) / {fmt(SQ)});")
            mx = ", ".join(f"var(--s{l}{h}i{i})" for i in range(pos + 1))
            lines.append(f"  --mx{l}{h}: max({mx});")
            den = " + ".join(f"exp(var(--s{l}{h}i{i}) - var(--mx{l}{h}))" for i in range(pos + 1))
            lines.append(f"  --dnm{l}{h}: calc({den});")
            for j in range(HD):
                col = h * HD + j
                num = " + ".join(
                    f"exp(var(--s{l}{h}i{i}) - var(--mx{l}{h})) * "
                    + (f"var(--V{l}p{i}j{col})" if i < pos else f"var(--{p}v{col})")
                    for i in range(pos + 1)
                )
                lines.append(f"  --{p}o{col}: calc(({num}) / var(--dnm{l}{h}));")
    lines.append("}")
    lev.append("\n".join(lines))
css.append("\n".join(lev))
css.append("")

# --- lm head, jitter, argmax (gen cells only) ---------------------------------

gc = ["/* lm head + argmax. only levels that actually speak pay for this */", ".gc {"]
qlm, slm = Q["lm"], S["lm"]
for k in range(V):
    terms = []
    for j in range(D):
        c = qlm[j][k]
        if c == 0:
            continue
        terms.append(("+ " if c > 0 else "- ") + f"var(--f{j})*{abs(c)}")
    body = "0 " + " ".join(terms) if terms else "0"
    jit = f"var(--tamp) * (mod(var(--sd) * {PJ[k]}, 97) / 96 - 0.5)"
    gc.append(f"  --lg{k}: calc({fmt(slm[k])} * ({body}) {sgn_term(k * TIE)} + {jit});")
gc.append("  --gmx: max(" + ", ".join(f"var(--lg{k})" for k in range(V)) + ");")
argmax = " + ".join(f"{k} * max(0, sign(var(--lg{k}) - var(--gmx) + {fmt(SEPS)}))" for k in range(1, V))
gc.append(f"  --np: calc({argmax});")
gc.append(f"  --s2: calc(mod(var(--sd) * 137 + 29, 251));")
gc.append(f"  --d2: max(var(--dn), calc(1 - min(1, abs(var(--np) - {END}))));")
gc.append("}")
css.append("\n".join(gc))
css.append("")

# glyph wrappers: accept the new token, advance the lcg, carry the done flag
css.append(".gw { --tk: var(--np); --sd: var(--s2); --dn: var(--d2); }")
css.append("")

# --- words on screen ----------------------------------------------------------
# leading space on words, none on punctuation, specials render nothing.


def glyph_text(tok):
    if tok in ("<p>", "<u>", "<b>", "<e>"):
        return ""
    if tok in (".", "!", "?"):
        return tok
    return " " + tok


gl = ["/* argmaxed integer -> word */"]
for t in range(V):
    gl.append(f'@container style(--tk: {t}) {{ .g::before {{ content: "{glyph_text(VOCAB[t])}"; }} }}')
gl.append('@container style(--dn: 1) { .g::before { content: ""; } }')
gl.append('@container style(--dn: 1) { .end::before { content: ""; } }')
css.append("\n".join(gl))
css.append("")

css.append(".page { --probe: calc(max(0, sign(mod(3, 2)))); }")
css.append("@container style(--probe: 1) { .warn { display: none; } }")

with open("model.css", "w", encoding="utf-8") as f:
    f.write("\n".join(css))


# --- index.html ---------------------------------------------------------------

radios = []
for qi in range(len(QUESTIONS)):
    radios.append(f'<input class="vh" type="radio" name="q" id="q{qi}"{" checked" if qi == DEFAULT_Q else ""}>')
for rid, _, _ in ROLLS:
    radios.append(f'<input class="vh" type="radio" name="roll" id="roll-{rid}"{" checked" if rid == DEFAULT_ROLL else ""}>')
for tid, _ in TAMPS:
    radios.append(f'<input class="vh" type="radio" name="tamp" id="tamp-{tid}"{" checked" if tid == DEFAULT_TAMP else ""}>')

qpills = "\n        ".join(f'<label for="q{i}">{q}</label>' for i, q in enumerate(QUESTIONS))
rpills = "\n        ".join(f'<label for="roll-{r}">{icon}</label>' for r, _, icon in ROLLS)
tpills = "\n        ".join(f'<label for="tamp-{t}">{t}</label>' for t, _ in TAMPS)

# the generation tree: 10 prompt levels, then speak levels
tree = '<span class="w gw"><span class="g"></span><span class="end"></span></span>'
for n in range(GEN - 1, 0, -1):
    pos = PROMPT + n - 1
    tree = f'<span class="w gw"><span class="g"></span><span class="cl p{pos} gc">{tree}</span></span>'
for pos in range(PROMPT - 1, -1, -1):
    gcls = " gc" if pos == PROMPT - 1 else ""
    tree = f'<span class="w pw{pos}"><span class="cl p{pos}{gcls}">{tree}</span></span>'

html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="a {N_PARAMS:,} parameter decoder-only chat transformer that runs entirely in css. real attention, rope, rmsnorm, swiglu, int8 matmuls, and a kv cache made of inherited custom properties. no javascript.">
<title>qwennie — a chat transformer in pure css</title>
<meta property="og:type" content="website">
<meta property="og:title" content="qwennie — a chat transformer in pure css">
<meta property="og:description" content="{N_PARAMS:,} parameters, two layers, real attention and a kv cache, all of it running in the style engine. not one line of javascript.">
<meta property="og:url" content="https://metrix187.github.io/qwennie/">
<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🐩</text></svg>">
<link rel="stylesheet" href="style.css">
<link rel="stylesheet" href="model.css">
</head>
<body>
{chr(10).join(radios)}
<div class="page">
  <header>
    <h1>qwennie<span class="paw">🐩</span></h1>
    <p class="tag">a {N_PARAMS:,} parameter chat transformer that lives entirely in css.
    real attention, rope, rmsnorm, swiglu, int8 matmuls, a kv cache made of
    inherited custom properties — and not one line of javascript. pick a
    message and she replies in a single style pass.</p>
  </header>
  <div class="warn">this browser is missing some css math (mod, sign, abs, exp, sqrt,
  &#64;property, or container style queries). qwennie needs chromium 138+, safari 18+, or
  firefox 151+ to think. she is not mad, just quiet.</div>
  <section class="controls" aria-label="chat controls">
    <div class="group"><span class="glabel">say</span>
        {qpills}
    </div>
    <div class="group"><span class="glabel">reroll</span>
        {rpills}
    </div>
    <div class="group"><span class="glabel">temperature</span>
        {tpills}
    </div>
  </section>
  <section class="chat">
    <div class="row user"><p class="bub um"></p></div>
    <div class="row bot"><span class="avatar">🐩</span><p class="bub qm">{tree}</p></div>
  </section>
  <footer>
    <p>she is a real decoder-only transformer: {L} layers, {HEADS} heads, d={D},
    context {T}. every token is one level of dom nesting. attention is unrolled
    per position — o(t&sup2;) in stylesheet bytes — and softmax runs on css exp().
    her matmul weights are int8 in weights.json, dequantized into calc() at build
    time. she was trained from scratch on a tiny original corpus; the name is a
    homage, no actual qwen weights are involved (they would be several gigabytes
    of stylesheet, and the browser would simply pass away).</p>
    <p>her big sister <a href="https://github.com/Metrix187/yipsy">yipsy</a> babbles
    prose next door. wtfpup licensed.</p>
  </footer>
</div>
</body>
</html>
"""
with open("index.html", "w", encoding="utf-8") as f:
    f.write(html)


# --- expected.json ------------------------------------------------------------
# same math as the stylesheet, plain python floats

import numpy as np  # only for convenience arrays in the reference pass

DQn = {k: np.array(v) for k, v in DQ.items()}
NRM = {k: np.array(v) for k, v in NORMS.items()}


def rms(x, g):
    r = 1.0 / math.sqrt(float((x * x).mean()) + EPS)
    return x * r * g


def sample(qtext, salt, tamp):
    ids = [PAD] * (PROMPT - 2 - len(qtext.split())) + [USR] + [stoi[x] for x in qtext.split()] + [BOT]
    kc = [[None] * L for _ in range(T)]
    vc = [[None] * L for _ in range(T)]

    def step(pos, tok):
        x = DQn["emb"][tok].copy()
        for l in range(L):
            a = rms(x, NRM[f"g1{l}"])
            q = (a @ DQn[f"wq{l}"]).reshape(HEADS, HD)
            k = (a @ DQn[f"wk{l}"]).reshape(HEADS, HD)
            v = (a @ DQn[f"wv{l}"]).reshape(HEADS, HD)
            for h in range(HEADS):
                for fq in range(HD // 2):
                    c, s = COS[pos][fq], SIN[pos][fq]
                    qe, qo = q[h, 2 * fq], q[h, 2 * fq + 1]
                    ke, ko = k[h, 2 * fq], k[h, 2 * fq + 1]
                    q[h, 2 * fq], q[h, 2 * fq + 1] = qe * c - qo * s, qe * s + qo * c
                    k[h, 2 * fq], k[h, 2 * fq + 1] = ke * c - ko * s, ke * s + ko * c
            kc[pos][l], vc[pos][l] = k, v
            o = np.zeros(D)
            for h in range(HEADS):
                sc = [float(q[h] @ kc[i][l][h]) / SQ for i in range(pos + 1)]
                mx = max(sc)
                es = [math.exp(z - mx) for z in sc]
                tot = sum(es)
                acc = np.zeros(HD)
                for i in range(pos + 1):
                    acc += (es[i] / tot) * vc[i][l][h]
                o[h * HD : (h + 1) * HD] = acc
            x = x + o @ DQn[f"wo{l}"]
            b = rms(x, NRM[f"g2{l}"])
            gate = b @ DQn[f"wg{l}"]
            up = b @ DQn[f"wu{l}"]
            x = x + ((gate / (1 + np.exp(-gate))) * up) @ DQn[f"wd{l}"]
        return rms(x, NRM["gf"]) @ DQn["lm"]

    for pos, tok in enumerate(ids):
        logits = step(pos, tok)
    s = salt
    words = []
    done = False
    cur = None
    for n in range(GEN):
        if cur is not None:
            logits = step(PROMPT + n - 1, cur)
        lj = [logits[k] + k * TIE + tamp * (((s * PJ[k]) % 97) / 96 - 0.5) for k in range(V)]
        cur = max(range(V), key=lambda kk: lj[kk])
        s = (s * 137 + 29) % 251
        if cur == END:
            done = True
        words.append("" if done else glyph_text(VOCAB[cur]))
    return "".join(words)


expected = {}
for qi, qtext in enumerate(QUESTIONS):
    for rid, salt, _ in ROLLS:
        for tid, tamp in TAMPS:
            expected[f"q{qi}|roll-{rid}|tamp-{tid}"] = sample(qtext, salt, tamp)
with open("expected.json", "w", encoding="utf-8") as f:
    json.dump({"combos": expected}, f, indent=1)

import os

print(f"model.css   {os.path.getsize('model.css'):>10,} bytes")
print(f"index.html  {os.path.getsize('index.html'):>10,} bytes")
print(f"combos      {len(expected)}")
for qi in (0, 1, 4, 9):
    key = f"q{qi}|roll-{DEFAULT_ROLL}|tamp-{DEFAULT_TAMP}"
    print(f"  [{QUESTIONS[qi]}]{expected[key]}")
